name: Release

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

permissions:
  contents: write # Needed to create releases and push tags

jobs:
  release: # Renamed job for clarity
    name: Create Release
    runs-on: ubuntu-20.04 # Changed runner to ensure GLIBC compatibility
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Fetch all history and tags for semantic-release
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Build binaries
        id: build
        run: |
          # Get version from semantic-release
          VERSION=${GITHUB_REF#refs/tags/}
          if [ "$VERSION" = "" ]; then
            VERSION="dev"
          fi

          # Get commit hash and build date
          COMMIT=$(git rev-parse --short HEAD)
          DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

          # Set ldflags for version injection
          LDFLAGS="-X main.version=${VERSION} -X main.commit=${COMMIT} -X main.date=${DATE}"

          mkdir -p dist

          GOOS=linux GOARCH=amd64 go build -ldflags "${LDFLAGS}" -o dist/accel-exporter-linux-amd64 ./cmd/accel-exporter
          GOOS=linux GOARCH=arm64 go build -ldflags "${LDFLAGS}" -o dist/accel-exporter-linux-arm64 ./cmd/accel-exporter
          GOOS=darwin GOARCH=amd64 go build -ldflags "${LDFLAGS}" -o dist/accel-exporter-darwin-amd64 ./cmd/accel-exporter
          GOOS=darwin GOARCH=arm64 go build -ldflags "${LDFLAGS}" -o dist/accel-exporter-darwin-arm64 ./cmd/accel-exporter

      - name: Create checksums
        run: |
          cd dist
          sha256sum * > checksums.txt
          cd .. # Go back to the root directory

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Configuration is now handled by .releaserc.json
